---
  minimum_pre_commit_version: 2.11.0
  default_stages: [commit, push, manual]
  repos:
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
        - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          args: [--max-line-length=88]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: [--filter-files]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.0.1
      hooks:
        - id: mypy
          language: system
    # - repo: https://github.com/pre-commit/mirrors-prettier
    #   rev: v2.7.1
    #   hooks:
    #     - id: prettier
    #       additional_dependencies:
    #         - prettier@2.8.1
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-added-large-files
    - repo: https://github.com/pycqa/pylint
      rev: v2.17.4
      hooks:
        - id: pylint
          args:
            [
              "--rcfile=setup.cfg"
            ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
        - id: trailing-whitespace
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: end-of-file-fixer
    # - repo: https://github.com/pytest-dev/pytest
    #   rev: "6.2.4"
    #   hooks:
    #   - id: pytest
    # - repo: https://github.com/categulario/test-coverage
    #   rev: "1.1.2"
    #   hooks:
    #   - id: test-coverage
    - repo: local
      hooks:
      - id: pytest
        name: Run pytest with coverage
        entry: pytest --cov=my_module
        language: system
        pass_filenames: false
