language_model:  
  service: "OpenAI"
  model_name: "gpt-35-turbo"
  deployment_name: "gpt-35-turbo"
  temp": 0.0
data_processing:
  data_folder_fp: "src/data/raw_data/rag_assistant_txt_files/"
  batch_size: 10
  chunk_size: 384
  overlap: 80
  embedding_model: "text-embedding-ada-002"
  embeddings_file_path: "src/data_processing/embeddings.csv"
  config_credentials: "src/config/credentials"
  meta_prefix: "meta_"
pinecone_db:
  index_name: "jarvis-index"
  dimension: 1536
  top_k: 5
  metric: "cosine"
  config_credentials: "config/credentials" 