usage_settings:
  agent_type: AzureOpenAIAssistant #LangchainOpenAIAgent OpenAIFunctionsAgent AzureOpenAIAssistant
  agent_prompt_config: rag_assistant
  vector_db: PineconeDatabaseHandler #PineconeDatabaseHandler ChromaDatabaseHandler
  embeddding_model_cls: OpenAIEmbeddingModel
  llm_service: azure
  function_call_prefix: $FUNCTION_CALL
language_models:  
  model_name: "gpt-4o"
  assistant_id: "asst_oa7DVd59BJQDxIEd0Dc9smfu"
  #model_name: "gpt-4-turbo"
  embedding_model: text-embedding-ada-002
  # deployment_name: "gpt-35-turbo"
  temp": 0.0
openai_tts:
  model: "alloy"
  speech_fp: "src/data/tmp_files"
document_processing:
  meta_data_pattern: '(?s)\$META_DATA(.*)\$END_META_DATA'
  part_seperator: "$PART$"
  chapter_seperator: "$CHAPTER$"
  subchapter_seperator: "$SUBCHAPTER$"
  meta_data_fields: ["document_name", "autor", "date", "genre", "field", "type", "user_id"]
data_processing:
  #data_folder_fp: "src/data/raw_data/rag_assistant_txt_files/"
  data_folder_fp: "src/data/raw_data/pdf_files"
  batch_size: 10
  chunk_size: 512
  overlap: 80
  embedding_model: "text-embedding-ada-002"
  embeddings_file_path: "src/data_processing/embeddings.csv"
  config_credentials: "src/config/credentials"
  meta_prefix: "meta_"
pinecone_db:
  index_name: "jarvis-index"
  dimension: 1536
  top_k: 5
  metric: "cosine"
  config_credentials: "config/credentials" 
chroma_db:
  collection_name: rag_vector_db
  chroma_db_fp: "src/data/chroma_db_instantiation/"
  dimension: 1536
  top_k: 5
  metric: "cosine"