{
  "data_processing":{
    "data_folder_fp": "src/data/raw_data/llm_assistant_txt_files/",
    "batch_size": 100,
    "chunk_size": 384,
    "overlap": 80,
    "embedding_model": "text-embedding-ada-002",
    "embeddings_file_path":"src/data_processing/embeddings.csv",
    "config_credentials":"src/config/credentials",
    "meta_prefix":"meta_",
  },
  "pinecone_db":{
    "index_name": "kkh-index",
    "dimension": 1536,
    "top_k": 5,
    "metric": "cosine",
    "config_credentials":"config/credentials",
  },
   "chroma_db":{
    "collection_name": "llm_assistant_txt_files",
    "data_folder_fp": "src/data/raw_data/",
    "config_credentials":"config/credentials",
    "persist_directory": "src/data/raw_data/chromadb_persistent",
    "embedding_model": "text-embedding-ada-002",
    "max_token_size": 256,
    "tokenizer_model": "text-davinci-003",

  },
}
